blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/pyyupsk/JSON-Viewer/discussions
    about: Use GitHub Discussions for questions and general discussion.
